"""
Pydantic models for Bonfire backend.
Defines the schema for communities, events, user context, and API requests/responses.
"""

from typing import Optional, List
from pydantic import BaseModel, Field
from datetime import datetime


class Community(BaseModel):
    """Represents a single community/club with comprehensive metadata."""
    id: str
    name: str
    acronym: Optional[str] = None
    city: str  # Delft, Den Haag, or Rotterdam
    category: str  # Main category (e.g., "Sports & Fitness", "Tabletop Gaming", "Culture")
    tags: List[str] = Field(default_factory=list)
    min_age: Optional[int] = None
    max_age: Optional[int] = None
    is_university_affiliated: bool = False
    institution: Optional[str] = None  # e.g., "TU Delft", "Independent"
    description_short: Optional[str] = None
    description_full: Optional[str] = None
    estimated_annual_fee_eur: Optional[float] = None
    primary_language: Optional[str] = None
    location_type: Optional[str] = None  # e.g., "Physical", "Online", "Hybrid"
    address: Optional[str] = None
    postal_code: Optional[str] = None
    website_url: Optional[str] = None
    instagram_url: Optional[str] = None
    contact_email: Optional[str] = None
    image_url: Optional[str] = None


class UserContext(BaseModel):
    """Represents user input and preferences for matching."""
    city: str  # Delft, Den Haag, or Rotterdam
    interests: str  # Free-form text: "I'm looking for board games and indie movies"
    experience_level: Optional[str] = None  # beginner, intermediate, expert, etc.
    age: Optional[int] = None  # Optional age for filtering by age range
    language: Optional[str] = None  # Preferred language


class CommunityMatch(BaseModel):
    """Represents a recommended community match for a user."""
    id: str
    name: str
    category: str
    city: str
    description_short: Optional[str] = None
    description_full: Optional[str] = None
    match_reason: str  # Generated by LLM explaining why this matches the user
    website_url: Optional[str] = None
    contact_email: Optional[str] = None
    image_url: Optional[str] = None
    estimated_annual_fee_eur: Optional[float] = None
    is_university_affiliated: bool = False
    relevance_score: Optional[float] = Field(default=None, ge=0, le=1)  # 0-1 confidence


class RecommendationRequest(BaseModel):
    """Request body for the /recommend endpoint."""
    city: str = Field(..., description="City: Delft, Den Haag, or Rotterdam")
    interests: str = Field(..., description="Free-form user interests (e.g., 'board games and bouldering')")
    limit: int = Field(default=5, ge=1, le=20, description="Max number of recommendations to return")


class RecommendationResponse(BaseModel):
    """Response body for the /recommend endpoint."""
    user_input: str
    city: str
    recommendations: List[CommunityMatch]
    total_count: int
    generated_at: str
